### ISSUE TITLE
Export fails with Xcode3Core crash

### ISSUE THREAD

**Issue by natalia-osa** [bitrise-io/steps-xcode-archive#100] opened 2018-01-04 17:21 UTC
I'm using _Xcode Archive & Export for iOS_ version _2.4.4_. Archiving succeeds, then export fails with `signal: error trap`. My current stack is: Xcode 9.1.x, on macOS 10.12 (Sierra).

Here is the output from _raw-xcodebuild-output.log_ (and that's where things start to be interesting):

```
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[__NSPlaceholderArray initWithObjects:count:] (in CoreFoundation)
  3   +[NSArray arrayWithObjects:count:] (in CoreFoundation)
  4   __55-[Xcode3CommandLineBuildTool _distributeArchiveAndExit]_block_invoke (in Xcode3Core)
  5   -[Xcode3CommandLineBuildTool _distributeArchiveAndExit] (in Xcode3Core)
  6   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
  7  0x00000001063512af (in xcodebuild)
  8   start (in libdyld.dylib)
```

Any idea what could go wrong and how to fix that?

**Comment by viktorbenei** [comment] 2018-01-06 11:20
Hi @natalia-osa ,

Duplicate of and I answered this at: https://discuss.bitrise.io/t/export-fails-with-xcode3core-crash/3643

Closing it here, feel free to comment at https://discuss.bitrise.io/t/export-fails-with-xcode3core-crash/3643 and we'll reply ASAP! :)

**Closed by viktorbenei** 2018-01-06 11:20 UTC
