### ISSUE TITLE
Properly exposes step outputs even if the step failed

### ISSUE THREAD

**Issue by chrsvl** [bitrise-io/steps-xcode-archive#8] opened 2015-09-21 14:36 UTC
As it was done for the Step Xcode Test :)
Thanks in advance!

**Comment by viktorbenei** [comment] 2015-09-22 05:47
For reference, this is the related `xcode-test` output: https://github.com/bitrise-io/steps-xcode-test/blob/master/step.yml#L108

**Comment by viktorbenei** [comment] 2015-09-22 05:48
sorry @chrsvl - this (the previous reference) was intended for our devs, to keep track of things when they (or me) get here to implement this ;)

**Comment by godrei** [comment] 2016-03-16 14:08
Hi @chrsvl ,
what dou you mean by `Properly exposes step outputs even if the step failed` ?

**Comment by viktorbenei** [comment] 2016-03-16 14:11
To be more precise - which outputs should be exposed even if the step fails? Only a generic `..._RESULT` output like https://github.com/bitrise-io/steps-xcode-test/blob/master/step.yml#L166 ?

**Comment by chrsvl** [comment] 2016-03-23 13:01
This is less necessary because we implemented a feature on our side to check users' certificates and mobile prov. But what I was originally asking for is an extract of Xcode's error message like "used umbrella header for import".

**Comment by viktorbenei** [comment] 2016-03-23 13:40
All right, thank you for the response!

We'll close this issue then, as it's a bit out of scope for this step - there's no single reliable way to find the error pattern in the log, and what exactly you'd want to expose as the error might depend on your use-case.

There's also a security concern to **not to** expose private information, which would also be too tricky to solve in a completely generic way.

Thanks again for the request, and feel free to open a new ticket if you'd have an issue or an idea how this could be solved!

**Closed by viktorbenei** 2016-03-23 13:40 UTC
Labels: enhancement
